import { User } from "../models/userschema.js";
import { catchAsyncError } from "./catchAsyncError.js";
import ErrorHandler from "./errorMiddleware.js";
import jwt from "jsonwebtoken"



//since only one token is taken resoleve the conflict so authentication +authorization together 
export const isAdminAuthenticated = catchAsyncError( async(req,res,next)=>
{
    const token = req.cookies.adminToken;//takes only the admin  if not token then admin not authenticated 
    if(!token)
        {
            return next(new ErrorHandler("Admin Not Authenticated!",400));

        }
    //take the token and verify using jwt that the token is generated by this web only
    const decoded = jwt.verify(token, process.env.JWT_SECRET_KEY);
    req.user = await User.findById(decoded.id); //takes the jwt id for authentication 
    if(req.user.role !== "Admin")
        {
            return next(
                new ErrorHandler(
                    `${req.user.role} not authorized for this resources!`,403
                )
            );
        }//for authorization that only the admin can add the admim not the patient 
        next();

});



//patientauthentication 
export const isPatientAuthenticated = catchAsyncError( async(req,res,next)=>
    {
        const token = req.cookies.patientToken;//takes only the patent  if not token then admin not authenticated 
        if(!token)
            {
                return next(new ErrorHandler("Patient Not Authenticated!",400));
    
            }
        //take the token and verify using jwt that the token is generated by this web only
        const decoded = jwt.verify(token, process.env.JWT_SECRET_KEY);
        req.user = await User.findById(decoded.id); //takes the jwt id for authentication 
        if(req.user.role !== "Patient")
            {
                return next(
                    new ErrorHandler(
                        `${req.user.role} not authorized for this resources!`,403
                    )
                );
            }//for authorization that only the admin can add the admim not the patient 
            next();
    
    });


    

